### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by burninghey** [Barleytree/Dupery#1] opened 2022-03-17 23:08 UTC
Hi, since last patch, steam oni crashes with dupery active. no other mods involved. then i installed mod updater. it shows me dupery is up to date, but when i enable dupery and restart, crash again. 

updating the mod revoked all my changes to override_personalites. I disabled all dupes with bad mods. Last time i checked, there were around 13 in the game. 

Error in GameAssets(Clone).Assets.OnPrefabInit 
System.NullReferenceException: Object reference not set to an instance of an object
  at Dupery.Db_Initialize.Postfix () [0x002c4] in <85d0f6807230451392fa99081ed32394>:0 
  at (wrapper dynamic-method) Db.Db.Initialize_Patch3(Db)
  at Db.Get () [0x0001c] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at Assets.CreatePrefabs () [0x00000] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at Assets.OnPrefabInit () [0x0027f] in <33cbadb4d53344698461e1b8bda03e57>:0 
  at KMonoBehaviour.InitializeComponent () [0x00068] in <53ba8544b0394db88dcaac034e1fe553>:0 

  at UnityEngine.Debug.LogError (System.Object message, UnityEngine.Object context) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at Debug.LogError (System.Object obj, UnityEngine.Object context) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at DebugUtil.LogErrorArgs (UnityEngine.Object context, System.Object[] objs) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at DebugUtil.LogException (UnityEngine.Object context, System.String errorMessage, System.Exception e) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at KMonoBehaviour.InitializeComponent () [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at KMonoBehaviour.Awake () [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent_Injected (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3& pos, UnityEngine.Quaternion& rot) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Internal_InstantiateSingleWithParent (UnityEngine.Object data, UnityEngine.Transform parent, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Transform parent) [0x00000] in <9fe2cbebfa394c8da6af069ec8cc9ef4>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.GameObject parent, System.String name) [0x00000] in <53ba8544b0394db88dcaac034e1fe553>:0 
  at LaunchInitializer.Update () [0x00000] in <33cbadb4d53344698461e1b8bda03e57>:0 
Build: U41-498381-
[HARDMODE.zip](https://github.com/Barleytree/Dupery/files/8294161/HARDMODE.zip)
S

**Comment by Barleytree** [comment] 2022-07-31 21:10
There've been some updates so this may be fixed now. Thank you for reporting either way, I can only close this because I can't reproduce the error.

I don't know why your override_personalites file was reset by an update, but someone else reported a similar issue so I'm working on it.

**Closed as completed by Barleytree** 2022-07-31 21:10 UTC
